[theme]
base = "dark"
primaryColor       = "#c8941a"
backgroundColor    = "#12141f"
secondaryBackgroundColor = "#1a1d2e"
textColor          = "#e2c97e"
font               = "sans serif"

[server]
maxUploadSize = 5
enableXsrfProtection = false
